### ISSUE TITLE
"usr" table name hardcoded in  lib.php:303

### ISSUE THREAD

**Issue by iv-enovation** [tonyjbutler/mahara#1]
$userid = get_record_sql('SELECT id FROM usr WHERE admin = 1 AND deleted = 0 ORDER BY id LIMIT 1', array());

**Comment by tonyjbutler** [comment]
Please report Mahara issues using the bug tracker at https://bugs.launchpad.net/mahara, following the guidelines at https://mahara.org/view/view.php?id=7. This repo is just a customised fork. Thanks.
